function tfSendToLogin(returnHash){try{sessionStorage.setItem('truefit-login-return',returnHash)}catch{}go('login')}
async function tfLogout(){try{await TF_AUTH.logout();toast('로그아웃되었습니다.');return true}catch(error){toast(tfAuthErrorMessage(error,'로그아웃하지 못했어요.'));return false}}
function authValidEmail(value){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}
function authValidPassword(value){return value.length>=8&&/[A-Za-z]/.test(value)&&/\d/.test(value)}
function authShell(body,switcher=''){
 flow.classList.add('auth-route');
 flow.innerHTML='<div class="auth-page"><div class="auth-wrap"><div class="auth-top"><a class="auth-back" href="#/">← TrueFit</a><span>'+switcher+'</span></div>'+body+'</div></div>';
 flow.querySelector('h1')?.focus({preventScroll:true});
 window.scrollTo(0,0);
}
function loginPage(){
 // TF-DEV: 데모 계정 안내 제거, 서버 로그인(TF_AUTH.login) 연결
 authShell(`<section class="auth-card"><span class="auth-eyebrow">WELCOME BACK</span><h1 tabindex="-1">다시 만나 반가워요</h1><p class="auth-sub">이메일과 비밀번호로 로그인하고, 저장해 둔 장바구니와 리포트를 이어가세요.</p>
 <form id="tf-login-form" novalidate><div class="auth-field"><label for="tf-login-email">이메일 *</label><input type="email" id="tf-login-email" autocomplete="email" placeholder="you@example.com" required></div>
 <div class="auth-field"><label for="tf-login-password">비밀번호 *</label><input type="password" id="tf-login-password" autocomplete="current-password" placeholder="비밀번호를 입력해 주세요" required></div>
 <div class="auth-row-between"><label class="auth-check-inline"><input type="checkbox" id="tf-login-remember"><span>로그인 상태 유지</span></label><button type="button" class="auth-link-button" id="tf-login-forgot">비밀번호를 잊으셨나요?</button></div>
 <p class="auth-forgot" id="tf-login-forgot-note" hidden>비밀번호 재설정은 아직 준비 중이에요.</p><p class="auth-error" id="tf-login-error" role="alert"></p>
 <button type="submit" class="auth-btn">로그인</button><p class="auth-switch">아직 계정이 없으신가요? <a href="#/signup">이메일로 회원가입 →</a></p></form></section>`, '아직 계정이 없으신가요? <a href="#/signup">회원가입</a>');
 const form=flow.querySelector('#tf-login-form'),email=flow.querySelector('#tf-login-email'),password=flow.querySelector('#tf-login-password'),error=flow.querySelector('#tf-login-error'),submit=form.querySelector('button[type=submit]');
 [email,password].forEach(input=>input.addEventListener('input',()=>{error.textContent='';input.classList.remove('auth-invalid')}));
 flow.querySelector('#tf-login-forgot').addEventListener('click',()=>{flow.querySelector('#tf-login-forgot-note').hidden=false});
 form.addEventListener('submit',async event=>{
  event.preventDefault();email.classList.remove('auth-invalid');password.classList.remove('auth-invalid');
  const emailValue=email.value.trim(),passwordValue=password.value;
  if(!authValidEmail(emailValue)){email.classList.add('auth-invalid');error.textContent='올바른 이메일 주소를 입력해 주세요.';return}
  if(!passwordValue){password.classList.add('auth-invalid');error.textContent='비밀번호를 입력해 주세요.';return}
  error.textContent='';tfBusy(submit,true,'로그인 중…');
  try{await TF_AUTH.login({email:emailValue,password:passwordValue,remember:flow.querySelector('#tf-login-remember').checked})}
  catch(err){tfBusy(submit,false);if(err.code==='invalid_credentials'){email.classList.add('auth-invalid');password.classList.add('auth-invalid')}error.textContent=tfAuthErrorMessage(err);return}
  let returnHash='';try{returnHash=sessionStorage.getItem('truefit-login-return')||'';sessionStorage.removeItem('truefit-login-return')}catch{}
  location.hash=returnHash&&!/^#\/(login|signup)\b/.test(returnHash)?returnHash:'#/';
 });
}
function signupPage(){
 authShell(`<section class="auth-card" id="tf-signup-view"><span class="auth-eyebrow">GET STARTED · EMAIL</span><h1 tabindex="-1">이메일로 시작하기</h1><p class="auth-sub">나에게 맞는 컴퓨터 구성과 육아용품 준비를, 계정에 저장하고 이어가세요.</p>
 <form id="tf-signup-form" novalidate><div class="auth-field"><label for="tf-signup-email">이메일 *</label><input type="email" id="tf-signup-email" autocomplete="email" placeholder="you@example.com" required><p class="auth-field-note" id="tf-signup-email-note"></p></div>
 <div class="auth-two-col"><div class="auth-field"><label for="tf-signup-password">비밀번호 *</label><input type="password" id="tf-signup-password" autocomplete="new-password" placeholder="영문·숫자 포함 8자 이상" required></div><div class="auth-field"><label for="tf-signup-password2">비밀번호 확인 *</label><input type="password" id="tf-signup-password2" autocomplete="new-password" placeholder="비밀번호 재입력" required></div></div><p class="auth-field-note" id="tf-signup-password-note"></p>
 <div class="auth-field"><label for="tf-signup-name">표시 이름 *</label><input type="text" id="tf-signup-name" placeholder="서비스에서 사용할 이름" maxlength="20" required></div>
 <div class="auth-terms"><label class="auth-term-all"><input type="checkbox" id="tf-agree-all"><span>전체 동의합니다</span></label>
 <div class="auth-term-item"><div class="auth-term-row"><label><input type="checkbox" class="tf-required-term"><span><b>[필수]</b> 이용약관 동의</span></label><details><summary>약관 전문 보기</summary><div class="auth-term-detail"><h3>제1조 (목적)</h3><p>이 약관은 TrueFit(이하 "회사")이 제공하는 컴퓨터·육아용품 구매 계획 서비스(이하 "서비스")의 이용과 관련하여 회사와 회원 간의 권리, 의무 및 책임사항을 규정함을 목적으로 합니다.</p><h3>제2조 (정의)</h3><p>① "회원"이란 이 약관에 동의하고 회사와 서비스 이용계약을 체결한 자를 말합니다.</p><p>② "게시물"이란 회원이 서비스 내에 게시한 리뷰, 후기, 댓글, 이미지 등의 정보를 말합니다.</p><h3>제3조 (약관의 효력 및 변경)</h3><p>① 이 약관은 서비스 화면에 게시함으로써 효력이 발생합니다.</p><p>② 회사는 관계 법령을 위반하지 않는 범위에서 약관을 변경할 수 있으며, 변경 시 적용일자와 변경 사유를 명시하여 시행일 이전에 공지합니다.</p><h3>제4조 (회원가입 및 자격)</h3><p>① 회원가입은 이용자가 약관 내용에 동의하고, 회사가 정한 절차에 따라 이메일 인증을 완료함으로써 성립합니다.</p><p>② 만 14세 미만인 자, 이미 회원 자격을 상실한 이력이 있는 자는 회원가입이 제한될 수 있습니다.</p><h3>제5조 (서비스의 제공 및 변경·중단)</h3><p>① 회사는 사용 목적과 예산에 맞춘 컴퓨터 구성 추천, 육아용품 준비 리스트 작성 등의 서비스를 제공합니다.</p><p>② 회사는 운영상·기술상의 필요에 따라 서비스의 전부 또는 일부를 변경하거나 중단할 수 있으며, 이 경우 사전에 공지합니다.</p><h3>제6조 (회원의 의무)</h3><p>회원은 리뷰·후기 등 게시물 작성 시 사실에 근거해야 하며, 허위 사실 또는 타인의 권리를 침해하는 내용을 게시해서는 안 됩니다.</p><h3>제7조 (게시물의 권리 귀속 및 활용)</h3><p>① 회원이 서비스 내에 작성한 리뷰, 후기, 댓글 등 게시물에 대한 저작권은 이를 작성한 회원 본인에게 귀속됩니다.</p><p>② 제1항에도 불구하고 회원의 게시물은 서비스의 운영, 홍보 및 마케팅 목적으로 회사가 운영하는 웹사이트·애플리케이션·SNS·광고물 등에 무상으로 사용될 수 있으며, 이 경우 회사는 게시물의 내용을 편집하거나 요약하여 사용할 수 있습니다.</p><p>③ 회원은 제2항에 따른 활용에 대해 언제든지 고객센터를 통해 이의를 제기하거나 철회를 요청할 수 있으며, 철회 시 회사는 지체 없이 해당 활용을 중단합니다.</p><h3>제8조 (면책조항)</h3><p>회사는 회원이 서비스를 통해 얻은 정보로 인해 발생한 손해에 대하여 책임을 지지 않으며, 상품 가격·리뷰·검증 결과는 실제 구매 판단의 근거로 사용할 수 없습니다.</p><h3>제9조 (분쟁해결 및 준거법)</h3><p>① 서비스 이용과 관련하여 회사와 회원 간에 분쟁이 발생한 경우, 양 당사자는 상호 협의를 통해 이를 해결하기 위해 노력합니다.</p><p>② 이 약관의 해석 및 회사와 회원 간의 분쟁에 대해서는 대한민국 법령을 적용합니다.</p><p class="auth-legal-note">※ 위 내용은 화면 구성을 위한 예시 약관이며, 실제 법적 효력을 갖는 문서가 아닙니다.</p></div></details></div></div>
 <div class="auth-term-item"><div class="auth-term-row"><label><input type="checkbox" class="tf-required-term"><span><b>[필수]</b> 개인정보 처리방침 동의</span></label><details><summary>전문 보기</summary><div class="auth-term-detail"><h3>수집 항목</h3><p>이메일 주소, 비밀번호(암호화 저장), 표시 이름</p><h3>이용 목적</h3><p>회원 식별 및 로그인, 저장한 장바구니·리포트 제공, 고객 문의 응대</p><h3>보유 기간</h3><p>회원 탈퇴 시 지체 없이 파기하며, 관계 법령에 따라 보관이 필요한 경우 해당 기간 동안 보관합니다.</p><h3>제3자 제공</h3><p>회사는 원칙적으로 회원의 개인정보를 외부에 제공하지 않습니다.</p><p class="auth-legal-note">※ 위 내용은 화면 구성을 위한 예시 문안이며, 정식 처리방침은 서비스 출시 시 안내됩니다.</p></div></details></div></div>
 <div class="auth-term-item"><div class="auth-term-row"><label><input type="checkbox" id="tf-agree-marketing"><span>[선택] 마케팅 정보 및 이벤트 수신 동의</span></label></div></div></div>
 <p class="auth-error" id="tf-signup-error" role="alert"></p><button type="submit" class="auth-btn">이메일로 회원가입</button><p class="auth-switch">이미 계정이 있으신가요? <a href="#/login">로그인</a></p></form></section>`, '이미 계정이 있으신가요? <a href="#/login">로그인</a>');
 // TF-DEV: 이메일 중복 확인·회원가입을 서버 API(TF_AUTH)로 연결
 const form=flow.querySelector('#tf-signup-form'),email=flow.querySelector('#tf-signup-email'),emailNote=flow.querySelector('#tf-signup-email-note'),password=flow.querySelector('#tf-signup-password'),password2=flow.querySelector('#tf-signup-password2'),passwordNote=flow.querySelector('#tf-signup-password-note'),agreeAll=flow.querySelector('#tf-agree-all'),required=[...flow.querySelectorAll('.tf-required-term')],terms=[...flow.querySelectorAll('.auth-terms input[type=checkbox]')].filter(input=>input!==agreeAll),submit=form.querySelector('button[type=submit]');
 let emailAvailable=null,emailTimer=null,emailCheckSeq=0;
 async function checkEmail(){const value=email.value.trim(),seq=++emailCheckSeq;email.classList.remove('auth-ok','auth-invalid');if(!value){emailAvailable=null;emailNote.textContent='';emailNote.className='auth-field-note';return}if(!authValidEmail(value)){emailAvailable=false;email.classList.add('auth-invalid');emailNote.textContent='올바른 이메일 형식으로 입력해 주세요.';emailNote.className='auth-field-note auth-bad-text';return}emailNote.textContent='이메일 확인 중…';emailNote.className='auth-field-note';try{const available=await TF_AUTH.checkEmail(value);if(seq!==emailCheckSeq)return;emailAvailable=available;email.classList.add(available?'auth-ok':'auth-invalid');if(available){emailNote.textContent='사용할 수 있는 이메일입니다. ✓';emailNote.className='auth-field-note auth-ok-text'}else{emailNote.innerHTML='이미 가입된 이메일입니다. <a href="#/login">로그인하기 →</a>';emailNote.className='auth-field-note auth-bad-text'}}catch(err){if(seq!==emailCheckSeq)return;emailAvailable=null;emailNote.textContent='지금은 중복 확인을 할 수 없어요. 가입할 때 다시 확인합니다.';emailNote.className='auth-field-note'}}
 function checkPasswords(){const first=password.value,second=password2.value;if(!first&&!second){passwordNote.textContent='';passwordNote.className='auth-field-note';password.classList.remove('auth-ok','auth-invalid');password2.classList.remove('auth-ok','auth-invalid');return}if(!authValidPassword(first)){password.classList.add('auth-invalid');passwordNote.textContent='영문과 숫자를 포함해 8자 이상으로 입력해 주세요.';passwordNote.className='auth-field-note auth-bad-text';return}password.classList.remove('auth-invalid');password.classList.add('auth-ok');if(second&&first!==second){password2.classList.add('auth-invalid');password2.classList.remove('auth-ok');passwordNote.textContent='비밀번호가 일치하지 않습니다.';passwordNote.className='auth-field-note auth-bad-text';return}password2.classList.remove('auth-invalid');if(second){password2.classList.add('auth-ok');passwordNote.textContent='사용할 수 있는 비밀번호입니다.';passwordNote.className='auth-field-note auth-ok-text'}else{passwordNote.textContent='';passwordNote.className='auth-field-note'}}
 email.addEventListener('input',()=>{clearTimeout(emailTimer);emailCheckSeq++;emailAvailable=null;email.classList.remove('auth-ok','auth-invalid');emailNote.textContent='';emailNote.className='auth-field-note';if(email.value.trim())emailTimer=setTimeout(checkEmail,400)});
 password.addEventListener('input',checkPasswords);password2.addEventListener('input',checkPasswords);agreeAll.addEventListener('change',()=>terms.forEach(input=>input.checked=agreeAll.checked));terms.forEach(input=>input.addEventListener('change',()=>{agreeAll.checked=terms.every(item=>item.checked)}));
 form.addEventListener('submit',async event=>{event.preventDefault();clearTimeout(emailTimer);const error=flow.querySelector('#tf-signup-error'),problems=[],emailValue=email.value.trim(),name=flow.querySelector('#tf-signup-name').value.trim();if(!authValidEmail(emailValue))problems.push('이메일을 확인해 주세요.');else if(emailAvailable===false)problems.push('이미 가입된 이메일입니다.');if(!authValidPassword(password.value))problems.push('비밀번호 조건을 확인해 주세요.');else if(password.value!==password2.value)problems.push('비밀번호가 일치하지 않습니다.');if(!name)problems.push('표시 이름을 입력해 주세요.');if(required.some(input=>!input.checked))problems.push('필수 약관에 동의해 주세요.');if(problems.length){error.textContent=problems[0];return}error.textContent='';tfBusy(submit,true,'가입 중…');try{await TF_AUTH.signup({email:emailValue,password:password.value,displayName:name,termsAgreed:!!(required[0]&&required[0].checked),privacyAgreed:!!(required[1]&&required[1].checked),marketingAgreed:flow.querySelector('#tf-agree-marketing').checked})}catch(err){tfBusy(submit,false);if(err.code==='email_taken'){emailAvailable=false;email.classList.remove('auth-ok');email.classList.add('auth-invalid')}error.textContent=tfAuthErrorMessage(err);return}let returnHash='';try{returnHash=sessionStorage.getItem('truefit-login-return')||'';sessionStorage.removeItem('truefit-login-return')}catch{}const next=returnHash&&!/^#\/(login|signup)\b/.test(returnHash)?returnHash:'#/';authShell('<section class="auth-card"><span class="auth-success-badge">✓</span><h1 tabindex="-1">회원가입이 완료되었습니다</h1><p class="auth-sub"><strong>'+esc(name)+'</strong>님, TrueFit에 오신 걸 환영해요.</p><a class="auth-btn" href="'+esc(next)+'">'+(next==='#/confirm'?'리스트 확정 계속하기 →':'TrueFit 시작하기 →')+'</a></section>')});
}
function accountPage(){
 // TF-DEV: 회원정보·비밀번호 변경·로그아웃·탈퇴(비밀번호 확인)를 서버 API(TF_AUTH)로 연결
 const session=TF_AUTH.user;if(!session){tfSendToLogin('#/account');return}
 authShell(`<section class="auth-card"><span class="auth-eyebrow">MY ACCOUNT</span><h1 tabindex="-1">회원정보 수정</h1><p class="auth-sub">표시 이름과 이메일을 최신 정보로 관리하세요.</p><form id="tf-profile-form" novalidate><div class="auth-field"><label for="tf-account-name">표시 이름 *</label><input type="text" id="tf-account-name" maxlength="20" required></div><div class="auth-field"><label for="tf-account-email">이메일 *</label><input type="email" id="tf-account-email" autocomplete="email" required><p class="auth-field-note" id="tf-account-email-note"></p></div><label class="auth-check-inline" style="margin-bottom:22px"><input type="checkbox" id="tf-account-marketing"><span>마케팅 정보 및 이벤트 수신 동의</span></label><p class="auth-error" id="tf-profile-error" role="alert"></p><p class="auth-field-note auth-ok-text" id="tf-profile-success" hidden>기본 정보가 저장되었습니다.</p><button type="submit" class="auth-btn">기본 정보 저장</button></form></section>
 <section class="auth-card"><span class="auth-eyebrow">SECURITY</span><h1>비밀번호 변경</h1><p class="auth-sub">주기적으로 비밀번호를 변경하면 계정을 더 안전하게 지킬 수 있어요.</p><form id="tf-password-form" novalidate><div class="auth-field"><label for="tf-current-password">현재 비밀번호 *</label><input type="password" id="tf-current-password" autocomplete="current-password"><p class="auth-field-note" id="tf-current-password-note"></p></div><div class="auth-two-col"><div class="auth-field"><label for="tf-new-password">새 비밀번호 *</label><input type="password" id="tf-new-password" placeholder="영문·숫자 포함 8자 이상" autocomplete="new-password"></div><div class="auth-field"><label for="tf-new-password2">새 비밀번호 확인 *</label><input type="password" id="tf-new-password2" placeholder="비밀번호 재입력" autocomplete="new-password"></div></div><p class="auth-error" id="tf-password-error" role="alert"></p><p class="auth-field-note auth-ok-text" id="tf-password-success" hidden>비밀번호가 변경되었습니다.</p><button type="submit" class="auth-btn">비밀번호 변경</button></form></section>
 <section class="auth-card auth-danger"><span class="auth-eyebrow">DANGER ZONE</span><h1>계정 관리</h1><p class="auth-sub">탈퇴하면 이메일·이름·비밀번호 등 계정 정보가 삭제되고 이 계정으로 다시 로그인할 수 없어요. 같은 이메일로는 다시 가입할 수 있습니다.</p><div class="auth-danger-row"><button type="button" class="auth-secondary-btn" id="tf-logout">로그아웃</button><button type="button" class="auth-danger-btn" id="tf-withdraw">회원 탈퇴</button></div><form id="tf-withdraw-form" novalidate hidden style="margin-top:22px"><div class="auth-field"><label for="tf-withdraw-password">현재 비밀번호 *</label><input type="password" id="tf-withdraw-password" autocomplete="current-password" placeholder="탈퇴하려면 비밀번호를 입력해 주세요"></div><p class="auth-error" id="tf-withdraw-error" role="alert"></p><div class="auth-danger-row"><button type="button" class="auth-secondary-btn" id="tf-withdraw-cancel">취소</button><button type="submit" class="auth-danger-btn">탈퇴하기</button></div></form></section>`, '<a href="#/">TrueFit으로 돌아가기</a>');
 const name=flow.querySelector('#tf-account-name'),email=flow.querySelector('#tf-account-email'),marketing=flow.querySelector('#tf-account-marketing'),emailNote=flow.querySelector('#tf-account-email-note');name.value=session.name||'';email.value=session.email||'';marketing.checked=!!session.marketing;
 let emailAvailable=true,emailTimer=null,emailCheckSeq=0;
 const handleAuthLost=err=>{if(err&&err.code==='unauthorized'){TF_AUTH._set(null);tfSendToLogin('#/account');return true}return false};
 async function checkAccountEmail(){const value=email.value.trim(),seq=++emailCheckSeq,own=value.toLowerCase()===String((TF_AUTH.user||{}).email||'').toLowerCase();email.classList.remove('auth-ok','auth-invalid');if(!value||own){emailAvailable=true;emailNote.textContent='';emailNote.className='auth-field-note';return}if(!authValidEmail(value)){emailAvailable=false;email.classList.add('auth-invalid');emailNote.textContent='올바른 이메일 형식으로 입력해 주세요.';emailNote.className='auth-field-note auth-bad-text';return}emailNote.textContent='이메일 확인 중…';emailNote.className='auth-field-note';try{const available=await TF_AUTH.checkEmail(value);if(seq!==emailCheckSeq)return;emailAvailable=available;email.classList.add(available?'auth-ok':'auth-invalid');emailNote.textContent=available?'사용할 수 있는 이메일입니다. ✓':'이미 다른 계정에서 사용 중인 이메일입니다.';emailNote.className='auth-field-note '+(available?'auth-ok-text':'auth-bad-text')}catch(err){if(seq!==emailCheckSeq)return;emailAvailable=null;emailNote.textContent='지금은 중복 확인을 할 수 없어요. 저장할 때 다시 확인합니다.';emailNote.className='auth-field-note'}}
 email.addEventListener('input',()=>{clearTimeout(emailTimer);emailCheckSeq++;emailAvailable=null;email.classList.remove('auth-ok','auth-invalid');emailNote.textContent='';emailNote.className='auth-field-note';emailTimer=setTimeout(checkAccountEmail,400)});
 const profileForm=flow.querySelector('#tf-profile-form');
 profileForm.addEventListener('submit',async event=>{event.preventDefault();clearTimeout(emailTimer);const error=flow.querySelector('#tf-profile-error'),success=flow.querySelector('#tf-profile-success'),submit=profileForm.querySelector('button[type=submit]'),nextName=name.value.trim(),nextEmail=email.value.trim(),current=TF_AUTH.user||{},changes={};success.hidden=true;if(!nextName){error.textContent='표시 이름을 입력해 주세요.';return}if(!authValidEmail(nextEmail)){error.textContent='이메일을 확인해 주세요.';return}if(emailAvailable===false){error.textContent='이미 사용 중인 이메일입니다.';return}error.textContent='';if(nextName!==current.name)changes.displayName=nextName;if(nextEmail.toLowerCase()!==String(current.email||'').toLowerCase())changes.email=nextEmail;if(marketing.checked!==!!current.marketing)changes.marketingAgreed=marketing.checked;if(!Object.keys(changes).length){success.hidden=false;return}tfBusy(submit,true,'저장 중…');try{await TF_AUTH.updateProfile(changes);success.hidden=false}catch(err){if(handleAuthLost(err))return;if(err.code==='email_taken'){emailAvailable=false;email.classList.remove('auth-ok');email.classList.add('auth-invalid')}error.textContent=tfAuthErrorMessage(err)}finally{tfBusy(submit,false)}});
 const passwordForm=flow.querySelector('#tf-password-form'),currentPassword=flow.querySelector('#tf-current-password'),newPassword=flow.querySelector('#tf-new-password'),newPassword2=flow.querySelector('#tf-new-password2');
 currentPassword.addEventListener('input',()=>{flow.querySelector('#tf-current-password-note').textContent='';currentPassword.classList.remove('auth-invalid')});[newPassword,newPassword2].forEach(input=>input.addEventListener('input',()=>{flow.querySelector('#tf-password-error').textContent=''}));
 passwordForm.addEventListener('submit',async event=>{event.preventDefault();const error=flow.querySelector('#tf-password-error'),success=flow.querySelector('#tf-password-success'),submit=passwordForm.querySelector('button[type=submit]');success.hidden=true;currentPassword.classList.remove('auth-invalid');if(!currentPassword.value){error.textContent='현재 비밀번호를 입력해 주세요.';return}if(!authValidPassword(newPassword.value)){error.textContent='새 비밀번호는 영문과 숫자를 포함해 8자 이상이어야 합니다.';return}if(newPassword.value!==newPassword2.value){error.textContent='새 비밀번호가 일치하지 않습니다.';return}if(newPassword.value===currentPassword.value){error.textContent='현재 비밀번호와 다른 비밀번호를 입력해 주세요.';return}error.textContent='';tfBusy(submit,true,'변경 중…');try{await TF_AUTH.changePassword({currentPassword:currentPassword.value,newPassword:newPassword.value});passwordForm.reset();success.hidden=false}catch(err){if(handleAuthLost(err))return;if(err.code==='invalid_password')currentPassword.classList.add('auth-invalid');error.textContent=tfAuthErrorMessage(err)}finally{tfBusy(submit,false)}});
 flow.querySelector('#tf-logout').addEventListener('click',async event=>{const button=event.currentTarget;tfBusy(button,true,'로그아웃 중…');if(await tfLogout())go('');else tfBusy(button,false)});
 const withdrawForm=flow.querySelector('#tf-withdraw-form'),withdrawButton=flow.querySelector('#tf-withdraw'),withdrawPassword=flow.querySelector('#tf-withdraw-password'),withdrawError=flow.querySelector('#tf-withdraw-error');
 withdrawButton.addEventListener('click',()=>{withdrawButton.hidden=true;withdrawForm.hidden=false;withdrawPassword.focus()});
 flow.querySelector('#tf-withdraw-cancel').addEventListener('click',()=>{withdrawForm.reset();withdrawForm.hidden=true;withdrawButton.hidden=false;withdrawError.textContent='';withdrawPassword.classList.remove('auth-invalid')});
 withdrawPassword.addEventListener('input',()=>{withdrawError.textContent='';withdrawPassword.classList.remove('auth-invalid')});
 withdrawForm.addEventListener('submit',async event=>{event.preventDefault();const submit=withdrawForm.querySelector('button[type=submit]');if(!withdrawPassword.value){withdrawPassword.classList.add('auth-invalid');withdrawError.textContent='현재 비밀번호를 입력해 주세요.';return}if(!window.confirm('정말 탈퇴하시겠어요? 계정 정보가 삭제되며 되돌릴 수 없어요.'))return;withdrawError.textContent='';tfBusy(submit,true,'탈퇴 처리 중…');try{await TF_AUTH.withdraw({password:withdrawPassword.value});toast('회원 탈퇴가 완료되었습니다.');go('')}catch(err){tfBusy(submit,false);if(handleAuthLost(err))return;if(err.code==='invalid_password')withdrawPassword.classList.add('auth-invalid');withdrawError.textContent=tfAuthErrorMessage(err)}});
}
