// TF-DEV: confirm.html 전용 — 리스트 확정(04) 화면. 비로그인이면 입력값을 임시 보관하고 로그인 후 이어온다.
const TF_CONFIRM_DRAFT_KEY='truefit-confirm-draft';
function confirmPage(){if(!tfPlan.listId)return go('category');const result=tfPlan.result;if(!result||result.list_id!==tfPlan.listId)return tfLoadResult(confirmPage,3);if(result.status!=='done'||!(result.totals&&result.totals.selected_units))return go('results');const auth=readAuthSession(),summary=tfListSummary(),pc=tfUiCategory(result.category)==='pc',today=new Date().toLocaleDateString('en-CA');let draft=null;try{draft=JSON.parse(sessionStorage.getItem(TF_CONFIRM_DRAFT_KEY)||'null')}catch{}if(!draft||draft.listId!==tfPlan.listId)draft=null;
 shell(heading('04 / SAVE YOUR PLAN','이 장바구니로 준비할까요?','이름과 구매 예정일, 목표 가격을 정해 나만의 계획으로 저장해요.')+`<div class="flow-grid"><div class="panel"><form id="confirm-form">${field('리스트 이름 *','name','text',draft?.name||summary?.name||(pc?'나의 첫 컴퓨터':'우리 아이 준비 리스트'),'required maxlength="60"')}${field('구매 예정일 *','date','date',draft?.date||today,'required min="'+today+'"')}${field('목표 총액 (원) *','target','number',draft?.target||Number(result.totals.selected_price||0),'required min="1" max="100000000"')}<label for="report-memo">메모</label><textarea id="report-memo" name="memo" maxlength="1000">${esc(draft?.memo||'')}</textarea><div class="line"></div><div class="notice">${auth?esc((auth.name||'회원')+'님 계정에 저장합니다.'):'로그인 후 리스트를 저장할 수 있습니다.'}</div><p id="confirm-error" class="error" role="alert"></p><div class="row" style="margin-top:20px">${btn('← 다시 살펴보기','results')}<button class="btn strong" type="submit">${auth?'리스트 확정하기':'로그인 후 확정하기'} →</button></div></form></div>${tfBasketAside(result)}</div>`,3)}
async function tfSubmitConfirm(form){const d=Object.fromEntries(new FormData(form)),error=flow.querySelector('#confirm-error'),submit=form.querySelector('button[type=submit]'),name=String(d.name||'').trim(),target=money(d.target);if(!name){error.textContent='리스트 이름을 입력해 주세요.';return}if(!d.date){error.textContent='구매 예정일을 선택해 주세요.';return}if(!(target>0)){error.textContent='목표 총액을 입력해 주세요.';return}if(tfPlan.result?.totals?.over_budget){error.textContent='예산을 초과했습니다. 추천 결과에서 구성을 조정해 주세요.';return}
 const draft={listId:tfPlan.listId,name,date:d.date,target,memo:String(d.memo||'')},saveDraft=()=>{try{sessionStorage.setItem(TF_CONFIRM_DRAFT_KEY,JSON.stringify(draft))}catch{}};
 if(!readAuthSession()){saveDraft();tfSendToLogin('confirm.html');return}
 if(tfPlan.busy)return;const listId=tfPlan.listId;tfPlan.busy=true;error.textContent='';tfBusy(submit,true,'저장하는 중…');
 try{const report=tfRequire(await TF_PLAN.confirm(listId,{name,planned_purchase_at:d.date,target_amount:target,memo:draft.memo}));try{sessionStorage.removeItem(TF_CONFIRM_DRAFT_KEY)}catch{}if(listId!==tfPlan.listId)return;tfPlan.report=report;tfPlan.listsLoaded=false;go('report')}
 catch(err){tfBusy(submit,false);if(err.code==='unauthorized'){TF_AUTH._set(null);saveDraft();tfSendToLogin('confirm.html');return}if(tfListGone(err))return;error.textContent=({no_items_selected:'장바구니에 담긴 품목이 없어요.',over_budget:'예산을 초과했습니다. 추천 결과에서 구성을 조정해 주세요.'})[err.code]||tfAuthErrorMessage(err)}
 finally{tfPlan.busy=false}}
confirmPage();
TF_AUTH.ready.then(()=>{if(tfPlan.listId&&!flow.querySelector('.result-overlay[open]'))confirmPage()}); // 로그인 여부에 따라 안내 문구·버튼이 달라져 다시 그린다
flow.addEventListener('submit',e=>{if(e.target.id!=='confirm-form')return;e.preventDefault();tfSubmitConfirm(e.target)});
