// TF-DEV: report.html 전용 — 리스트 리포트(05) 화면. 로그인 필요 — 서버 로그인 확인이 끝난 뒤 그린다.
function tfOnListRenamed(id){if(tfPlan.report&&tfPlan.report.list_id===id)reportPage()}
function reportPage(){if(!tfPlan.listId)return go('category');const r=tfPlan.report;if(!r||r.list_id!==tfPlan.listId){tfLoadThen(reportPage,4,()=>TF_PLAN.report(tfPlan.listId).then(data=>{tfPlan.report=tfRequire(data)}).catch(err=>{if(err.status===404&&err.code==='not_found'){tfPlan.report={list_id:tfPlan.listId,status:'none'};return}if(err.code==='unauthorized'){TF_AUTH._set(null);tfSendToLogin('report.html');return}throw err}));return}
 if(r.status==='none'){shell(heading('05 / MY REPORT','저장된 리포트가 없어요.')+`<div class="panel empty"><p>추천 리스트를 확정하면 구매 계획을 다시 볼 수 있어요.</p>${btn('추천 결과 보기','results','strong')}</div>`,4);return}
 const items=r.items||[],watch=r.price_watch||{},watchText=({waiting:'추적 대기 · 아직 수집된 가격이 없어요',tracking:'가격 추적 중',reached:'목표가 도달'})[watch.status]||'추적 대기';
 const rows=items.map(item=>'<tr><td class="report-photo-cell">'+partThumbnail(item.slot_label,item.product?.image_url)+'</td><td><strong>'+esc(item.slot_label)+'</strong><br>'+esc(item.product?.name)+(Number(item.qty)>1?' × '+Number(item.qty):'')+'<br><button class="report-product-link" type="button" data-plan-product-url="'+esc(item.product?.purchase_url||'')+'" aria-label="'+esc(item.product?.name)+' 상품 페이지 열기">상품 페이지 ↗</button></td><td>'+won(Number(item.price||0)*Math.max(1,Number(item.qty)||1))+'</td><td><div class="report-review-metric">'+tfReviewMetric(item.review)+'</div></td><td>'+esc(item.evidence_text||'')+'</td></tr>').join('');
 shell(`<div class="report-banner"><div class="flow-logo" style="color:#e4dccf">PLAN SAVED / MY REPORT</div><h1 tabindex="-1">${esc(r.name)}</h1><p class="muted">${esc(r.owner_display_name||'회원')}님의 계획 · ${esc(r.planned_purchase_at)} 구매 예정</p><div class="row spread"><div><div class="muted">예상 총액</div><div class="sum">${won(r.total)}</div></div><div><div class="muted">목표 가격</div><div class="sum">${won(r.target_amount)}</div></div></div></div><div class="row no-print" style="margin-bottom:22px">${btn('리포트 인쇄 / PDF','print')}${btn('리스트 파일 저장','download')}${btn('추천 다시 보기','results')}</div><div class="panel"><h2>구매 리스트</h2><div class="table-wrap"><table class="report-product-table"><thead><tr><th>제품 사진</th><th>제품</th><th>가격</th><th>리뷰</th><th>추천 근거</th></tr></thead><tbody>${rows}</tbody><tfoot><tr><th colspan="2">전체 가격</th><td colspan="3"><strong class="report-total-price">${won(r.total)}</strong></td></tr></tfoot></table></div><p class="muted">${esc(r.memo||'추가 메모가 없습니다.')}</p></div><div class="two"><div class="panel"><h2>가격 추적</h2><div class="notice">현재 상태: ${esc(watchText)}${watch.latest_total!=null?' · 최근 합계 '+won(watch.latest_total):''}</div></div><div class="panel"><h2>알림 설정</h2><label class="checklabel"><input type="checkbox" id="alert-pref" ${watch.enabled?'checked':''}>목표가 도달 시 알림 받기</label><p class="muted">목표가 ${won(watch.target_amount??r.target_amount)} 이하가 되면 알려드려요.</p><p id="alert-error" class="error" role="alert"></p></div></div><p class="muted">${r.confirmed_at?'확정 시점 '+esc(new Date(r.confirmed_at).toLocaleString('ko-KR')):''}</p>`,4)}
async function tfToggleAlert(input){const r=tfPlan.report,error=flow.querySelector('#alert-error');if(!r)return;input.disabled=true;try{const data=tfRequire(await TF_PLAN.alert(tfPlan.listId,{enabled:input.checked,target_amount:r.target_amount}));r.price_watch=data.price_watch||r.price_watch;toast(input.checked?'목표가 알림을 켰어요.':'목표가 알림을 껐어요.');reportPage()}catch(err){input.checked=!input.checked;input.disabled=false;if(err.code==='unauthorized'){TF_AUTH._set(null);tfSendToLogin('report.html');return}if(error)error.textContent=tfAuthErrorMessage(err)}}

// 로그인 필요 화면 — 서버에서 로그인 상태를 확인할 때까지 기다린 뒤 그리거나 로그인으로 보낸다.
shell(tfStatusPanel('로그인 상태를 확인하고 있어요…'),4);
TF_AUTH.ready.then(()=>{if(!readAuthSession()){toast('로그인 후 이용해 주세요.',true);tfSendToLogin('report.html');return}reportPage()});
flow.addEventListener('change',e=>{if(e.target.id==='alert-pref')tfToggleAlert(e.target)});
