"""Reproducible Korean final corpus report from saved validation and read-back artifacts."""
import json
from pathlib import Path
from collections import Counter
ROOT=Path('outputs/review_full_corpus/20261002_authorized')
def read(n):return json.loads((ROOT/n).read_text())
def main():
 audit=read('final_readback_audit.json');account=read('effective_all_record_accounting.json');scope=read('semantic_review_scope.json');cost=read('cost_and_attempt_accounting.json');before=read('db_before.json');after=audit['db_counts'];review=read('semantic_review.json');rows=read('canonical_results.json');sem=audit['personal_review_decisions'];tests=read('test_report.json')
 (ROOT/'db_current_readback.json').write_text(json.dumps({k:after[k] for k in before},ensure_ascii=False,indent=2)+'\n')
 empty=Counter('approved' if review.get(r['review']['document_id'],{}).get('decision')=='accepted' and r['status']=='validated_candidate' else r['status'] for r in rows if not r['result']['observations'])
 lines=['# 전체 리뷰 원문 적재·Luna 관측·종합 결과','','동결한 전체 관측 대상5,655문서의944/944배치 결과를 수집했고 미응답은0입니다. DB에는 실제 원문5,653개, 규칙102개, 개인 승인 관측45건이 있습니다. 전체 canonical 관측 초안3,676건은 상품·속성·맥락·방향별로 종합했고, 승인 DB 관측과 미검토/불확실/수정 필요 초안을 분리했습니다. 전체 실제 기록5,859개를 모두 DB에 넣었다고 주장하지 않습니다.','', '## 전체 기록 회계와 원문 적재','','| 구분 | 기록 수 |','|---|---:|',f'| canonical 실제+합성 전체 | {account["total_records"]} |',f'| 실제 원문 DB 적재 | {account["loaded"]} |',f'| 정확한 catalog 대응 없음 | {account["unmapped"]} |',f'| 명시적 원문-상품 충돌 | {account["source_target_conflict"]} |',f'| 실제 기록이나 빈 본문 | {account["empty_body"]} |',f'| 합성: 운영 적재·관측 제외 | {account["synthetic_excluded"]} |','','실제5,859 = 적재5,653 + 미대응195 + 충돌2 + 빈 본문9입니다. 모든 기록의 파일·행·ID·사유는 effective_all_record_accounting.json과 source_manifest.json에 있습니다. README/원본 provenance에 따라5개 processed canonical stream을 선택했고 raw JSON/XLSX/CSV 중복 컨테이너를 별도 적재하지 않았습니다. 원본 해시·건수를 대조했습니다. PC 원본의1,900개 미확보 null slot은 수집 공백이며 실제 리뷰로 만들지 않았습니다.','','제조사·전체 모델/구별 가능한 문자 모델코드와 catalog 기본 옵션을 결정적으로 대응했습니다. 임의 fuzzy/LLM 상품 추측이나 상품 생성은 없습니다. RAM 모델 용량과 catalog 주요 스펙을 대조했습니다. LG 지역 suffix와 Samsung G80SD 별칭은 로컬 공식 seed 링크/32인치4K240Hz OLED 기본 모델 증거로 연결했습니다. 세부 retail SKU를 새로운 상품으로 만들지 않았으며 SSD catalog의 capacity-option 모델 특성은 원문 근거에 보존했습니다. catalog525개는 그대로입니다.','','미대응195개는 GK898B33, GK888B Mini30, U2723QE83, 이전 세대 Studio Display24, MPG271QRX7, PA279CV6, S3222DGM5, 27MK600M3, MPG341CQPX3, LS27DG500ENXZA1입니다. 비슷한 PRO/다른 모델·세대 상품에 붙이지 않았습니다. 외부 신뢰 가능한 모델 증거/실제 catalog 등록이 필요한 잔여 범위입니다.','','처음5,655개를 적재한 뒤 개인 검토에서2건의 명시적 다른 모델 경험을 확인했습니다: Magnetox 2XL 문서에 POLARIS2 실제 사용, LG27GP850 문서에 LG27GL850/Acer 실제 사용. 이번 실행 소유·원문 동일·관측/embedding/aggregate 없음 가드를 확인한2개만 보상 트랜잭션으로 제거했습니다. 원본·첫 관측·immutable provenance는 보존하고 tombstone으로 잘못된 재적재를 막았습니다. legacy 데이터는 제거하지 않았습니다. 이름 없는 sister-model 경험1건은 원문을 보존하되 관측 승인을 보류합니다.','','## 배치·검증·승인 범위','','| 관측 문서 분류 | 수 |','|---|---:|']
 for k,v in audit['document_status_counts'].items():lines.append(f'| {k} | {v} |')
 lines+=['',f'기계 오류 문서만 최대1회, {cost["targeted_retry_batch_files"]}개 retry 파일/{cost["targeted_retry_unique_documents"]}문서를 재시도했습니다. 첫 raw와 재시도는 모두 보존했습니다.1건은 첫 결과 duplicate key, 재시도 forbidden metadata로 계약 검증에 계속 실패해 격리했습니다. 누락/실패를 빈 성공으로 바꾸거나 의미 답안을 알려 통과시키지 않았습니다.','',f'빈 canonical 관측 결과의 분류: {dict(empty)}. 빈 결과도 직접 검토한 구성요소별 표본에 포함했습니다.','',f'개인 의미 검토697문서, 미검토{audit["not_personally_reviewed_documents"]}문서입니다. 모든 partial/불확실·기계실패·상품 충돌·기계 재시도 회복 위험을 검토했고 위험 검토 미완료는{len(scope["risk_review_pending_documents"])}입니다. 나머지는12개 구성요소별 비어있지 않은 결과/빈 결과, 짧은 원문·중간 길이 등의 공개된 체계적 표본입니다. 대표 표본이나 전수 의미 품질 감사가 아닙니다.','', '| 개인 검토 판정 | 문서 수 |','|---|---:|']
 for k,v in sorted(sem.items()):lines.append(f'| {k} | {v} |')
 lines+=['','accepted70문서만 원문·결과 hash와 기계 검증을 다시 확인해 기존 importer로 반영했습니다. 승인 문서 중 빈 결과도 있으므로 DB 관측 수는45건입니다. 동일 승인 재적용 후45건 그대로임을 확인했습니다. 검토 판정은 source-grounded 개인 판단이며 전체 corpus의 gold label/error rate가 아닙니다. 70개 correction_needed에는 명확한 누락/환각과 동결 기준 적용 문제가 포함되며, 해석 차이는 interpretation_uncertain으로 별도 보류했습니다. 기계적으로 유효한 후보5,066개를 일괄 승인하지 않았습니다.','','확인한 오류 예: 2열 수냉→240mm 추정, 근거에 없는 fanless/USB포트/리셋버튼/키보드 매크로·교환 경험 요약, RX590 비교 발열 감소 누락, 가능하다는 M.2 설명을2개 실제 장착으로 변경, 이미지 만족·입력 누락·RGB 조건 배터리 부족 평가의 누락/잘못된 unmapped 진단. 동일 근거 ID 복원은 문자열 정확성을 보장하지만 의미 적합성/완전성까지 보장하지 않습니다. 해당 결과는 승인하지 않았습니다.','','BIOS 편의 경험, 숫자 온도+미래 발열 경고, 일반적 안정성 표현, 다른 상품/과거 경험 귀속, 가정적인 케이블 불편 등은 실제 원문 맥락에 따라 불확실성을 기록했습니다. 다른 평가자의 해석을 자동 정답으로 가정하거나 반복 의미 재시도로 지우지 않았습니다.','','## 규칙·계약·DB 검증','','PC82개 v6 정의는 그대로 유지했고 주변기기20개는 concrete actual-use functional-v1 계약을 신규 동결했습니다. 버전 review-aspect-v6-prod-20261002; 실제 UUID와 짧은 구성요소별 rule key 매핑을 고정했습니다. 초기 k=4는 잠정 운영 선택이며 품질 개선/추천 점수 계산을 뜻하지 않습니다. 원문에는 모든 문자와 순서를 보존한 span을 한 번만 제공합니다. 코드가 span ID를 정확한 원문으로 복원하고 unknown/cross-doc IDs·구성요소/버전 불일치·거짓 invalid_input을 거부합니다. 기존 canonical importer JSON과 whole-review 저장/embedding 설계는 유지했습니다.','','요약은 근거의 모든 setup 정보를 반복할 필요는 없지만 qualification/상반 평가를 지우거나 설정별 경험을 일반화하면 안 됩니다. 조건을 prose/evidence로 보존한다고 추천 필터가 자동 적용되는 것은 아니며, 향후 추천 사용 전 조건의 기계적 표현 설계가 필요합니다. 불확실/partial/error는 추천·점수화에 들어가지 않습니다.','','| DB 테이블 | 실행 전 | 완료 후 |','|---|---:|---:|']
 for t,v in before.items():lines.append(f'| {t} | {v} | {after[t]} |')
 lines+=['','legacy evidence.review_summary69건도 유지했습니다. 적재5,653개 전부의 UUID/상품/원문/메타데이터 및 등록 규칙102개를 동결 manifest와 읽기 전용 전수 대조했습니다.944배치의 input/wire/keys2,832파일 재생성·해시 검증과 원본 불변 검증을 통과했습니다. 이전 v4/v5/v6 체크섬 파일23/35/55개는 그대로이며 이전 pilot의 database_import_allowed=false도 바꾸지 않았습니다. schema/migration 변경, embedding, Q/R, 추천 점수/aggregate 계산, commits는 하지 않았습니다.','','원문 importer는 insert-only/idempotent이며 변경 원문은 관측/embedding 재구축이 필요한 충돌로 거부합니다. SQL 오류는 전체 트랜잭션 rollback합니다. 초기 dict.values SQL 순서 문제를 rollback 후 명시적 컬럼 순서로 수정했습니다. 실DB 검증은 의도된 적재/읽기 검증이며 테스트는 개발 DB에서 실행하지 않았습니다.','',f'격리 truefit_test_UUID + TRUEFIT_REQUIRE_TEST_DB=1 필수 seed 기반 관련5개 test suite {tests["passed"]}passed, skip0. 후속 aggregate 보호 test2passed, skip0. full pytest는 실행하지 않았습니다.','', '## 종합·비용·재현','','consolidated_observation_drafts.json: 모든 canonical 관측3,676건과 승인/보류 근거. consolidated_product_aspect_direction.json: 상품·속성·맥락·방향별 승인/불확실/미검토 counts. confirmed_database_observations.json / confirmed_product_aspect_direction.json: 실제 DB 승인45건의 별도 종합. 점수는 계산하지 않았습니다.','',f'실제 토큰은 도구가 제공하지 않아 unmeasured입니다. first raw944개, 대상5,655문서, retry15개/17문서, 위임 그룹{cost["worker_assignment_groups"]}, wire 문자{cost["input_characters_proxy"]:,}는 작업량 proxy입니다. backend 모델 호출 횟수/실제 토큰 절감을 주장하지 않습니다. Luna medium/fork none만 사용했고 최대2작업자를 병행했습니다.','','```bash','PYTHONPATH=. UV_CACHE_DIR=/tmp/uv-cache uv run python db/audit_review_corpus_sources.py','PYTHONPATH=. UV_CACHE_DIR=/tmp/uv-cache uv run python db/consolidate_review_corpus.py','PYTHONPATH=. UV_CACHE_DIR=/tmp/uv-cache uv run python db/pending_review_corpus.py --group-size 100','PYTHONPATH=. UV_CACHE_DIR=/tmp/uv-cache uv run python db/import_review_corpus_approved.py','PYTHONPATH=. UV_CACHE_DIR=/tmp/uv-cache uv run python db/consolidate_review_observations.py','PYTHONPATH=. UV_CACHE_DIR=/tmp/uv-cache uv run python db/final_audit_review_corpus.py','PYTHONPATH=. UV_CACHE_DIR=/tmp/uv-cache uv run python db/report_review_corpus.py','```','','resume_queue.json은0개입니다. 원래 frozen source 전체를 db/seed_review_corpus.py --apply로 다시 실행하면 확정 충돌2건의 tombstone 때문에 전체 쓰기가 거부되도록 설계되어 있습니다. tombstone을 해제하거나 이전 manifest를 바꿔 재적재하지 마십시오. 새 catalog/원문 증거 확보 시195개 미대응만 별도의 검토 manifest로 추가해야 합니다. 남은1개 기계 실패 및 미승인 초안은 first raw/진단에 보존되어 있으며 무제한 재시도 대상이 아닙니다. 전체 준비된 관측 수집·종합은 완료됐고, 실제 source 전체5859개의 적재 완료와 전수 의미 승인은 달성한 것으로 표현하지 않습니다.','','주요 산출물: effective_all_record_accounting.json, source_manifest.json + supplement, canonical_source_audit.json, mapping_consistency_checks.json, rules.json/rule_policy.json, frozen_input_checksums.json, worker_assignments.json, batches/*의 first raw/retry/canonical/validation, semantic_review.json/semantic_review_scope.json, source_target_conflicts.json/source_compensation_receipts, observation_import_receipts, final_readback_audit.json, cost_and_attempt_accounting.json, test_report.json, artifact_checksums.json.']
 (ROOT/'review_report.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'report':str(ROOT/'review_report.md'),'db_documents':account['loaded'],'db_observations':after['evidence.review_aspect_observation'],'pending':audit['pending_batches'],'personal_reviews':697},ensure_ascii=False))
if __name__=='__main__':main()
